import "@/src/app/globals.css";
import Header from "./components/Header";

import localFont from "next/font/local";

export const vazirmatnLight = localFont({
  src: "../../public/fonts/Vazirmatn/Vazirmatn-RD-Light.woff2",
  weight: "300",
  style: "normal",
  variable: "--font-vazirmatn-light",
});

export const vazirmatnRegular = localFont({
  src: "../../public/fonts/Vazirmatn/Vazirmatn-RD-Regular.woff2",
  weight: "400",
  style: "normal",
  variable: "--font-vazirmatn-regular",
});

export const vazirmatnBold = localFont({
  src: "../../public/fonts/Vazirmatn/Vazirmatn-RD-Bold.woff2",
  weight: "700",
  style: "normal",
  variable: "--font-vazirmatn-bold",
});

export const metadata = {
  title: "Coffe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={vazirmatnRegular.className}>
      <body className="relative flex flex-col items-center min-h-screen mx-auto bg-coffee-gradient ">
        <Header />
        {children}
      </body>
    </html>
  );
}
